import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "./ui/button";

interface AnalysisResultProps {
  result: string;
  onClear: () => void;
}

export const AnalysisResult = ({ result, onClear }: AnalysisResultProps) => {
  return (
    <Card className="w-full max-w-2xl text-left">
      <CardHeader>
        <div className="flex justify-between items-center">
          <div>
            <CardTitle>Analysis Results</CardTitle>
            <CardDescription>
              Generated by Google Gemini 1.5 Flash
            </CardDescription>
          </div>
          <Button variant="outline" onClick={onClear}>
            Analyze Another
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <div className="prose prose-sm dark:prose-invert max-w-none">
          <pre className="whitespace-pre-wrap font-sans text-sm">
            {result}
          </pre>
        </div>
      </CardContent>
    </Card>
  );
};