// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nlxpocoavmjhleacfaul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5seHBvY29hdm1qaGxlYWNmYXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5NTQzNjksImV4cCI6MjA3OTUzMDM2OX0.bLRiCdI-vywi4qZ3tYsYOGYXV-aoj-ht623YVpD2U80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);